[build]
  command = "bun prisma migrate deploy && bun prisma generate && bun run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"
